services:
  public-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5174:5174"  # Cambiado de 5173 a 5174 para evitar conflictos
    volumes:
      - .:/app
      - /app/node_modules
      - ./certs:/app/certs
    environment:
      - NODE_ENV=development
    networks:
      - my-shared-network

networks:
  my-shared-network:
    driver: bridge